version: '2'
services:
  bot-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/bot/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
